#include "joshua/cpu.hpp"
#include "joshua/instruction.hpp"
#include <iostream>
#include <vector>

using namespace joshua;
// Simple integer stream generated by check_vectors.py. No JSON dependency in the core.
int main() {
    Bus bus; auto ram = std::make_shared<Memory>(65536, false); bus.map({"RAM", 0, 65536, ram});
    unsigned count = 0, failures = 0;
    std::string name;
    auto registers = [] {
        unsigned pc, a, x, y, sp, p;
        std::cin >> pc >> a >> x >> y >> sp >> p;
        return Registers{static_cast<Word>(pc), static_cast<Byte>(a), static_cast<Byte>(x), static_cast<Byte>(y), static_cast<Byte>(sp), static_cast<Byte>(p)};
    };
    while (std::cin >> name) {
        Cpu cpu(bus); cpu.r = registers();
        unsigned size; std::cin >> size;
        for (unsigned i = 0; i < size; ++i) { unsigned address, value; std::cin >> address >> value; ram->patch(static_cast<Word>(address), static_cast<Byte>(value)); }
        auto expected = registers(); std::cin >> size;
        std::vector<std::pair<unsigned, unsigned>> memory(size);
        for (auto& [address, value] : memory) std::cin >> address >> value;
        std::cin >> size;
        std::vector<BusCycle> expectedCycles(size), actual;
        for (auto& cycle : expectedCycles) { unsigned value; std::cin >> cycle.address >> value >> cycle.write; cycle.data = static_cast<Byte>(value); }
        if (!std::cin) { std::cerr << "Malformed vector stream\n"; return 2; }
        bus.trace = [&](auto cycle) { actual.push_back(cycle); };
        cpu.step(); bus.trace = {};
        bool functional = cpu.r.pc == expected.pc && cpu.r.a == expected.a && cpu.r.x == expected.x &&
            cpu.r.y == expected.y && cpu.r.sp == expected.sp && cpu.r.p == expected.p;
        for (auto [address, value] : memory) functional &= bus.peek(static_cast<Word>(address)) == value;
        bool timing = actual.size() == expectedCycles.size();
        if (timing) for (std::size_t i = 0; i < actual.size(); ++i)
            timing &= actual[i].address == expectedCycles[i].address && actual[i].data == expectedCycles[i].data && actual[i].write == expectedCycles[i].write;
        if (!functional || !timing) {
            ++failures;
            if (failures <= 4) {
                std::cerr << name << " functional=" << functional << " bus=" << timing << " A=" << hex(cpu.r.a, 2) << '/' << hex(expected.a, 2)
                    << " P=" << hex(cpu.r.p, 2) << '/' << hex(expected.p, 2) << '\n';
                std::cerr << " expected:"; for (auto c : expectedCycles) std::cerr << ' ' << hex(c.address) << (c.write ? 'W' : 'R') << hex(c.data, 2);
                std::cerr << "\n actual:  "; for (auto c : actual) std::cerr << ' ' << hex(c.address) << (c.write ? 'W' : 'R') << hex(c.data, 2);
                std::cerr << '\n';
            }
        }
        ++count;
    }
    std::cout << count << " cases, " << failures << " failures\n";
    return failures ? 1 : 0;
}
